# Generated by Django 5.2.4 on 2025-07-21 18:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_accesslog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescription',
            name='hash',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='prescription_id',
            field=models.CharField(max_length=20),
        ),
    ]
