# Generated by Django 5.2.4 on 2025-07-25 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_prescription_hash_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='phone',
            field=models.CharField(default='Not Provided', max_length=15),
            preserve_default=False,
        ),
    ]
