# Generated by Django 5.2.4 on 2025-07-25 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_patient_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='doctor_group',
            field=models.CharField(default='General', max_length=100),
            preserve_default=False,
        ),
    ]
