# Generated by Django 5.2.4 on 2025-07-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('core', '0005_doctor_doctor_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='doctor_group',
        ),
        migrations.AddField(
            model_name='doctor',
            name='groups',
            field=models.ManyToManyField(related_name='doctor_members', to='auth.group'),
        ),
    ]
